ss-latency:
  command:
    highValue: 50
    lowValue: 50
    periodMs: 0
    startTimeMs: 0
    offPeriodMs: 0
    percentErrors: 0.0

pulse-latency:
  command:
    highValue: 500
    lowValue: 50
    periodMs: 10000
    startTimeMs: 0
    offPeriodMs: 5000
    percentErrors: 0.0

sine-latency:
  command:
    highValue: 500
    lowValue: 50
    periodMs: 10000
    startTimeMs: 0
    offPeriodMs: 0
    percentErrors: 0.0

ramp-latency:
  command:
    highValue: 500
    lowValue: 50
    periodMs: 10000
    startTimeMs: 0
    offPeriodMs: 0
    percentErrors: 0.0